### PR TITLE
using postgres to store jira and clickup accounts

### PR DESCRIPTION
**Pull request by astreter**
Since each Slack channel can have own list/project or even own account in ClickUp and Jira it's inconvenient to keep all such data in env config.go

Following modules are used:
Postgres client: github.com/go-pg/pg/v10
db migrations: github.com/go-pg/migrations/v8

INSLY-1120

### CODE REVIEW

**Comment by kuzaxak** [comment]
Task linked: [INSLY-1120 Jiraclick: Store Jira and ClickUp credentials to Postgres](https://app.clickup.com/t/2454960/INSLY-1120)

**Comment by astreter** [comment]
!deploy

**Comment by astreter** [comment]
!deploy

**Comment by astreter** [comment]
!deploy

**Pull request merged**
