### PR TITLE
Migrate jiraclick app to AWS HDO Beta cluster

### PR DESCRIPTION
**Pull request by AlexanderPavlovHC**
Add a Jenkinsfile to enable deploying the application through Jenkins instead of GitHub Actions. Migrate Postgres db from OD to AWS RDS. The application is deployed to an AWS HDO Beta cluster

### CODE REVIEW

**Comment by qdo-deployer** [comment]
## Infrastructure changes detected


### beta

<details><summary>Output</summary>

```diff

********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
slack-bot, jiraclick, Ingress (networking.k8s.io) has been added:
- 
+ # Source: jiraclick/templates/ingress.yaml
+ apiVersion: networking.k8s.io/v1
+ kind: Ingress
+ metadata:
+   name: jiraclick
+   labels:
+     helm.sh/chart: jiraclick-0.1.0
+     app.kubernetes.io/name: jiraclick
+     app.kubernetes.io/instance: jiraclick
+     app.kubernetes.io/version: "c8f9321"
+     app.kubernetes.io/managed-by: Helm
+   annotations:
+     kubernetes.io/ingress.class: nginx
+     kubernetes.io/tls-acme: "true"
+ spec:
+   tls:
+     - hosts:
+         - "jiraclick.k9s.qdo.ee"
+       secretName: jiraclick.k9s.qdo.ee-tls
+   rules:
+     - host: "jiraclick.k9s.qdo.ee"
+       http:
+         paths:
+         - path: /
+           pathType: Prefix
+           backend:
+             service:
+               name: jiraclick
+               port:
+                 name: http-handler
slack-bot, jiraclick, Secret (v1) has been added:
+ # Source: jiraclick/templates/secret.yaml
+ apiVersion: v1
+ kind: Secret
+ metadata:
+   labels:
+     app.kubernetes.io/instance: jiraclick
+     app.kubernetes.io/managed-by: Helm
+     app.kubernetes.io/name: jiraclick
+     app.kubernetes.io/version: c8f9321
+     helm.sh/chart: jiraclick-0.1.0
+   name: jiraclick
+ data:
+   postgres_url: '++++++++ # (104 bytes)'
+   rabbitmq_url: '++++++++ # (138 bytes)'

slack-bot, jiraclick, Service (v1) has been added:
- 
+ # Source: jiraclick/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: jiraclick
+   labels:
+     helm.sh/chart: jiraclick-0.1.0
+     app.kubernetes.io/name: jiraclick
+     app.kubernetes.io/instance: jiraclick
+     app.kubernetes.io/version: "c8f9321"
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   type: ClusterIP
+   ports:
+     - port: 80
+       targetPort: http-handler
+       protocol: TCP
+       name: http-handler
+     - port: 9090
+       targetPort: http-metrics
+       protocol: TCP
+       name: http-metrics
+   selector:
+     app.kubernetes.io/name: jiraclick
+     app.kubernetes.io/instance: jiraclick
+     role: api
slack-bot, jiraclick, ServiceAccount (v1) has been added:
+ # Source: jiraclick/templates/serviceaccount.yaml
+ apiVersion: v1
+ kind: ServiceAccount
+ metadata:
+   name: jiraclick
+   labels:

+     helm.sh/chart: jiraclick-0.1.0
+     app.kubernetes.io/name: jiraclick
+     app.kubernetes.io/instance: jiraclick
+     app.kubernetes.io/version: "c8f9321"
+     app.kubernetes.io/managed-by: Helm
slack-bot, jiraclick-api, Deployment (apps) has been added:
- 
+ # Source: jiraclick/templates/deployment-api.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: jiraclick-api
+   labels:
+     helm.sh/chart: jiraclick-0.1.0
+     app.kubernetes.io/name: jiraclick
+     app.kubernetes.io/instance: jiraclick
+     app.kubernetes.io/version: "c8f9321"
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: jiraclick
+       app.kubernetes.io/instance: jiraclick
+       role: api
+   template:
+     metadata:
+       annotations:
+         sidecar.opentelemetry.io/inject: "true"
+       labels:
+         app.kubernetes.io/name: jiraclick
+         app.kubernetes.io/instance: jiraclick
+         role: api
+     spec:
+       imagePullSecrets:
+         - name: registry-qdo
+       serviceAccountName: jiraclick
+       securityContext:
+         {}
+       containers:
+         - name: webhooks
+           securityContext:
+             {}
+           image: "096568705843.dkr.ecr.eu-west-1.amazonaws.com/jiraclick:c8f9321"
+           imagePullPolicy: IfNotPresent
+           command: [ "/app" ]
+           args:
+             - http-handler
+           env:
+             
+             - name: DEBUG
+               value: "true"
+             - name: RABBITMQ_URL
+               valueFrom:
+                 secretKeyRef:
+                   key: rabbitmq_url
+                   name: jiraclick
+             - name: POSTGRES_URL
+               valueFrom:
+                 secretKeyRef:
+                   key: postgres_url
+                   name: jiraclick
+             - name: POSTGRES_INSECURE
+               value: "true"
+             - name: CONFIG_PATH
+               value: "/"
+             - name: HTTPHANDLER_PORT
+               value: "8080"
+             - name: HTTPHANDLER_PORT
+               value: "8080"
+             - name: METRICS_PORT
+               value: "9090"
+           envFrom:
+             - configMapRef:
+                 name: opentelemetry-config
+           ports:
+             - name: http-handler
+               containerPort: 8080
+               protocol: TCP
+             - name: http-metrics
+               containerPort: 9090
+               protocol: TCP
+           livenessProbe:
+             httpGet:
+               path: /health-check
+               port: http-handler
+           readinessProbe:
+             httpGet:
+               path: /health-check
+               port: http-handler
+           resources:
+             {}
slack-bot, jiraclick-worker, Deployment (apps) has been added:
- 
+ # Source: jiraclick/templates/deployment-worker.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: jiraclick-worker
+   labels:
+     helm.sh/chart: jiraclick-0.1.0
+     app.kubernetes.io/name: jiraclick
+     app.kubernetes.io/instance: jiraclick
+     app.kubernetes.io/version: "c8f9321"
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: jiraclick
+       app.kubernetes.io/instance: jiraclick
+       role: worker
+   template:
+     metadata:
+       annotations:
+         sidecar.opentelemetry.io/inject: "true"
+       labels:
+         app.kubernetes.io/name: jiraclick
+         app.kubernetes.io/instance: jiraclick
+         role: worker
+     spec:
+       imagePullSecrets:
+         - name: registry-qdo
+       serviceAccountName: jiraclick
+       securityContext:
+         {}
+       containers:
+         - name: opsgenie
+           securityContext:
+             {}
+           image: "096568705843.dkr.ecr.eu-west-1.amazonaws.com/jiraclick:c8f9321"
+           imagePullPolicy: IfNotPresent
+           command: [ "/app" ]
+           args:
+             - worker
+           env:
+             
+             - name: DEBUG
+               value: "true"
+             - name: RABBITMQ_URL
+               valueFrom:
+                 secretKeyRef:
+                   key: rabbitmq_url
+                   name: jiraclick
+             - name: POSTGRES_URL
+               valueFrom:
+                 secretKeyRef:
+                   key: postgres_url
+                   name: jiraclick
+             - name: POSTGRES_INSECURE
+               value: "true"
+             - name: CONFIG_PATH
+               value: "/"
+             - name: HTTPHANDLER_PORT
+               value: "8080"
+             - name: METRICS_PORT
+               value: "9090"
+           envFrom:
+             - configMapRef:
+                 name: opentelemetry-config
+           ports:
+             - name: http-metrics
+               containerPort: 9090
+               protocol: TCP
+           resources:
+             {}

```
</details>

---
**Warning**: This is preview of the plan, actual plan may change during the     **deploy** stage if the `master` branch was changed in between.

* :arrows_counterclockwise: To plan again, push a new commit or comment:
  * `!plan`



*Last updated at 2023/08/30 13:31:34*

**Review by kuzaxak — APPROVED** [review]

**Comment by AlexanderPavlovHC** [comment]
!deploy

**Comment by qdo-deployer** [comment]
Deploy failed or was aborted. @AlexanderPavlovHC, please check the logs [here](https://ci.beta.hdo.ee/job/Github%20CI/job/jiraclick/job/PR-34/3/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/jiraclick/job/PR-34/3//console)).

**Comment by AlexanderPavlovHC** [comment]
!deploy

**Comment by AlexanderPavlovHC** [comment]
!deploy

**Comment by qdo-deployer** [comment]
Deploy failed or was aborted. @AlexanderPavlovHC, please check the logs [here](https://ci.beta.hdo.ee/job/Github%20CI/job/jiraclick/job/PR-34/4/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/jiraclick/job/PR-34/4//console)).

**Comment by qdo-deployer** [comment]
Deploy failed or was aborted. @AlexanderPavlovHC, please check the logs [here](https://ci.beta.hdo.ee/job/Github%20CI/job/jiraclick/job/PR-34/5/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/jiraclick/job/PR-34/5//console)).

**Comment by AlexanderPavlovHC** [comment]
!deploy

**Comment by qdo-deployer** [comment]
@AlexanderPavlovHC, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/jiraclick/job/PR-34/6/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/jiraclick/job/PR-34/6//console)).

**Pull request merged**
